apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: load-generator
  labels:
    app: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
        - name: load-generator
          image: ghcr.io/voize-gmbh/devops-case-study/load-generator:v1
          env:
            - name: ML_API_URL
              value: "http://ml-api.ml-api.svc.cluster.local:8000"
            - name: BACKEND_API_URL
              value: "http://backend-api.backend-api.svc.cluster.local:8000"
            - name: REQUEST_INTERVAL_MS
              value: "2000"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
