{
 "title": "Backend API",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Statuses",
   "type": "timeseries",
   "description": "Statuses for endpoints excluding /health and /ready",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (exported_endpoint, status) (rate(backend_api_requests_total{exported_endpoint!=\"/health\", exported_endpoint!=\"/ready\"}[5m])) * 300",
     "legendFormat": "{{exported_endpoint}} {{status}}"
    }
   ]
  },
  {
   "title": "Backend Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(exported_endpoint) (rate(backend_api_request_duration_seconds_sum[2m]))\n/\nsum by(exported_endpoint) (rate(backend_api_request_duration_seconds_count[2m]))\n* 1000",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by(endpoint, le) (\n    rate(backend_api_request_duration_seconds_bucket[2m])\n  )\n) * 1000",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by(endpoint, le) (\n    rate(backend_api_request_duration_seconds_bucket[2m])\n  )\n) * 1000",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Open DB Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (backend_api_db_connections_active)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status) (rate(backend_api_db_queries_total[5m])) * 300",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}