{
 "title": "ML API",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ML API Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(status) (rate(ml_api_requests_total[5m])) * 300",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ML API Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(ml_api_request_duration_seconds_sum[2m])) / sum(rate(ml_api_request_duration_seconds_count[2m])) * 1000",
     "legendFormat": "Latency in ms"
    }
   ]
  },
  {
   "title": "ML Predictions",
   "type": "timeseries",
   "description": "Total number of ML predictions performed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(ml_api_predictions_total[5m])) * 300",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ML Memory Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (ml_api_memory_bytes)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}