alertmanager:
  enabled: true

grafana:
  enabled: true

prometheus:
  prometheusSpec:
    retention: 14d
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
    podMonitorNamespaceSelector: { }
    serviceMonitorNamespaceSelector: { }
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector:
      matchLabels:
        app.kubernetes.io/component: monitoring
  serviceMonitor:
    selfMonitor: false
  additionalServiceMonitors: [ ]

