alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m

    route:
      receiver: mock-webhook
      group_by: [ 'alertname', 'namespace', 'severity' ]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h

    receivers:
      - name: mock-webhook
        webhook_configs:
          - url: 'https://alerts.voize.de'
            send_resolved: true


grafana:
  enabled: true
  defaultDashboardsEnabled: false

prometheus:
  prometheusSpec:
    retention: 14d
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
    podMonitorNamespaceSelector: { }
    serviceMonitorNamespaceSelector: { }
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector:
      matchLabels:
        app.kubernetes.io/component: monitoring
  serviceMonitor:
    selfMonitor: false
  additionalServiceMonitors: [ ]

