apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - flux-podmonitor.yaml
  - backend-api-servicemonitor.yaml
  - ml-api-servicemonitor.yaml
  - alerts/backend-api.yaml
  - alerts/ml-api.yaml
configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards/control-plane.json
      - dashboards/cluster.json
      - dashboards/logs.json
      - dashboards/backend-api.json
      - dashboards/ml-api.json
      - dashboards/namespaces.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: flux-grafana-datasources
    files:
      - datasources/loki.yaml
    options:
      labels:
        grafana_datasource: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
        kustomize.toolkit.fluxcd.io/substitute: disabled