apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ml-api
spec:
  namespaceSelector:
    matchNames:
      - ml-api
  selector:
    matchLabels:
      app: ml-api
  endpoints:
    - port: http