fullnameOverride: "fluent-bit"

flush: 1
logLevel: info

config:
  inputs: |
    [INPUT]
        Name         tail
        Path         /var/log/containers/*.log
        Exclude_Path /var/log/containers/*_logging_*.log
        Parser       cri
        Tag          kube.*

  filters: |
    [FILTER]
        Name         kubernetes
        Match        kube.*
        Merge_Log    On
        Keep_Log     Off
        Merge_Log_Key log
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Kube_Tag_Prefix  kube.var.log.containers.
        Annotations      Off
        Labels           On

  outputs: |
    [OUTPUT]
        name  loki
        match kube.*
        host  loki
        port  3100
        labels namespace=$kubernetes['namespace_name'], pod_name=$kubernetes['pod_name'], container_name=$kubernetes['container_name'], app=$kubernetes['labels']['app'], service=$kubernetes['labels']['service']
