apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: backend-api
  labels:
    app: backend-api
spec:
  selector:
    app: backend-api
  ports:
    - port: 8000
      targetPort: http
      name: http
